### ISSUE TITLE
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1)

### ISSUE THREAD

**Issue by pablocalcagnino** [bitrise-steplib/steps-danger#10]
I'm getting an error when running this step in my CI and locally. I could bypass the error with --no-verify-ssl locally. Working under Github Enterprise and maybe the cert of my company is not valid.

I could fork the repo and introduce an extra parameter to indicate if ssl verification should be done (defaults to true) but I have no experience in Go.

Maybe this feature/solution could help more people.

Working Example:
`bundle exec danger pr https://github.corp.XXX.com/XXXX/pull/1 **--no-verify-ssl**`

**Comment by Roland-Bak** [comment]
Thanks for being awesome and sharing your workaround, @pablocalcagnino ! :)

We'd also be happy to take a look at the issue and see if there are other possible solutions, could you please send us the URL of the build and enable Support Access on the Settings tab of the app (https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) ?
