### ISSUE TITLE
Support multiple Dangerfile by `dangerfile` and `danger_id` options

### ISSUE THREAD

**Issue by asapo** [bitrise-steplib/steps-danger#11]
Hi!

I hope `steps-danger` to support multiple Dangerfiles.
I have two `Dangerfile`s.

1. danger for lint. this can comment lint messages **before** compile.
2. danger for test coverage. this can comment test coverage **after** compile.

Danger has `--dangerfile` and `--danger_id` options:
https://github.com/danger/danger/blob/cc95f8a64af8441ae9c9c40b497f072c8dd1afec/lib/danger/commands/runner.rb#L64-L65

I am glad that they can be specified through this step.

**Comment by istx25** [comment]
Hi @asapo,

Thank you for reaching out.

I have marked this down in our internal feature request tracker. This is something we may get to in the future but I can not say if or when that would happen. With that said, we'd be more than happy to review a community pull request implementing this functionality.

Cheers,
Luna

**Comment by asapo** [comment]
This issue was fixed by #12 🎉
