### ISSUE TITLE
Issue with Github access

### ISSUE THREAD

**Issue by afaucogney** [bitrise-steplib/steps-danger#16]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.0.2
- Is the issue reproducible with the latest version? _YES_
- Does the issue happen sporadically, or every time?  _EVERY TIME_
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? _NOT APPLICABLE_

### Issue description

- Danger Step doesn't work on my Android app github repo
- I'm use to run similar configuration with Gitlab with sucess
- I'm using the same configuration for the iOS app, and the step run well (same token, same step config in xml)

### Bitrise info

- Build URL: https://app.bitrise.io/build/a149addeb891fa3d#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 

<details>
  <pre>
+------------------------------------------------------------------------------+

| (0) danger                                                                   |
+------------------------------------------------------------------------------+
| id: danger                                                                   |
| version: 2.0.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-01-15T11:19:05Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
$ danger "--version"
Could not determine danger vesion: exec: "danger": executable file not found in $PATH
Config:
- RepositoryURL: @github.com:[REDACTED]/[REDACTED]-mobile-android.git
- AdditionalOptions: --fail-on-errors=true
- GithubAPIToken: *****
- GithubHost: 
- GithubAPIBaseURL: 
- GitlabAPIToken: 
- GitlabHost: 
- GitlabAPIBaseURL: 
Checking dependencies
Bundler...
Bundler installed
Installing dependencies from your gem file
$ bundle "install"
Fetching gem metadata from https://rubygems.org/.............
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Using addressable 2.7.0
Fetching ansi 1.5.0
Installing ansi 1.5.0
Fetching ast 2.4.1
Installing ast 2.4.1
Using bundler 1.17.2
Using claide 1.0.3
Using colored2 3.1.2
Fetching cork 0.3.0
Installing cork 0.3.0
Using nap 1.1.0
Fetching open4 1.3.4
Installing open4 1.3.4
Fetching claide-plugins 0.9.2
Installing claide-plugins 0.9.2
Fetching multipart-post 2.1.1
Installing multipart-post 2.1.1
Fetching ruby2_keywords 0.0.2
Installing ruby2_keywords 0.0.2
Fetching faraday 1.1.0
Installing faraday 1.1.0
Fetching faraday-http-cache 2.2.0
Installing faraday-http-cache 2.2.0
Fetching rchardet 1.8.0
Installing rchardet 1.8.0
Fetching git 1.7.0
Installing git 1.7.0
Fetching rexml 3.2.4
Installing rexml 3.2.4
Fetching kramdown 2.3.0
Installing kramdown 2.3.0
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching no_proxy_fix 0.1.2
Installing no_proxy_fix 0.1.2
Fetching sawyer 0.8.2
Installing sawyer 0.8.2
Fetching octokit 4.19.0
Installing octokit 4.19.0
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Fetching danger 8.2.1
Installing danger 8.2.1
Fetching danger-plugin-api 1.0.0
Installing danger-plugin-api 1.0.0
Fetching ruby-ll 2.1.2
Installing ruby-ll 2.1.2 with native extensions
Fetching oga 3.3
Installing oga 3.3 with native extensions
Fetching danger-android_lint 0.0.8
Installing danger-android_lint 0.0.8
Fetching danger-kotlin_detekt 0.0.3
Installing danger-kotlin_detekt 0.0.3
Bundle complete! 3 Gemfile dependencies, 31 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Running danger
$ bundle "exec" "danger" "--fail-on-errors=true"
bundler: failed to load command: danger (/Users/vagrant/.rbenv/versions/2.6.5/bin/danger)
Faraday::ConnectionFailed: Failed to open TCP connection to git.[REDACTED].com:443 (getaddrinfo: nodename nor servname provided, or not known)
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:945:in `connect'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:919:in `start'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:144:in `request_via_get_method'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:135:in `request_with_wrapped_block'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:128:in `perform_request'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:70:in `block in call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/adapter.rb:61:in `connection'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:68:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/response.rb:11:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/response.rb:11:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/octokit-4.19.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/octokit-4.19.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/request/retry.rb:148:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/rack_builder.rb:154:in `build_response'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/connection.rb:492:in `run_request'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.1.0/lib/faraday/connection.rb:198:in `get'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/octokit-4.19.0/lib/octokit/connection.rb:156:in `request'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/octokit-4.19.0/lib/octokit/connection.rb:19:in `get'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/octokit-4.19.0/lib/octokit/client/pull_requests.rb:33:in `pull_request'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/danger-8.2.1/lib/danger/request_sources/github/github.rb:121:in `fetch_details'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/danger-8.2.1/lib/danger/danger_core/environment_manager.rb:52:in `fill_environment_vars'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/danger-8.2.1/lib/danger/danger_core/dangerfile.rb:276:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/danger-8.2.1/lib/danger/danger_core/executor.rb:29:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/danger-8.2.1/lib/danger/commands/runner.rb:73:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/danger-8.2.1/bin/danger:5:in `<top (required)>'
  /Users/vagrant/.rbenv/versions/2.6.5/bin/danger:23:in `load'
  /Users/vagrant/.rbenv/versions/2.6.5/bin/danger:23:in `<top (required)>'
Failed to run bundle exec danger, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | danger (exit code: 1)                                         | 38.79 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-danger/issues        |
| Source: https://github.com/bitrise-steplib/steps-danger                      |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

1. Just run Danger

**Comment by afaucogney** [comment]
The only diff I saw between working ios and android is the following log 

RepositoryURL: @github.com:[REDACTED]/[REDACTED]-mobile-android.git

Nothing is redacted for iOS, but the config looks the same.

**Comment by cathyharmon** [comment]
Hello,

For the Danger step, the value you have for the **Repository URL of your project** input variable looks strange.   The default value is $GIT_REPOSITORY_URL.   It looks like you may have tried to specify the value, but left the $ sign at the front.

Can you try setting the value back to the default or removing the $ in the value?

cathy

**Comment by afaucogney** [comment]
Hi @cathyharmon, I just fixed it and start a build. I will let you know.

**Comment by afaucogney** [comment]
@cathyharmon nothing changed, I think in any case it does look at the main git repo url, is'nt it ?

**Comment by afaucogney** [comment]
Bitrise support ticket is : https://bitrise.zendesk.com/hc/en-us/requests/10953

**Comment by afaucogney** [comment]
We had conflicts with unused envvar !
